name: Pandurang
on:
  push:
    branches:
      - 'Master'
jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
      - name: test
        uses: actions/checkout@v2
      - name: hellow world pandurang is there
        run: echo "hellow world pandurang is there"

        name: Upload Artifact
        uses: actions/upload-artifact@v2
        with: 
         name: workflow_steps
         path: workflow_steps_status.csv
